### ISSUE TITLE
Authentication always returns successful? SP2010

### ISSUE THREAD

**Issue by incredibleweirdo** [jimmywim/SPMobile#2]
Hello,
    This was the perfect thing for a project I am working on. My company has a large sharepoint install, SP 2010, authenticated with domain credentials. I've begun the work on an internal app which will be utilized for uploading photos to a sharepoint list. The issue I am having during testing is that authentication is always successful - even if the URL is malformed, or I enter the incorrect user name and password. Am I doing something wrong?

Here's the relevant method that is initiating the authentication (in a view controller which is also the delegate):

``` objective-c
- (IBAction)connectSharepoint:(id)sender
{
    userName = [_userNameField text];
    userPassword = [_userPasswordField text];


    FormsAuth *auth;
    auth = [[FormsAuth alloc] initWithUsernamePasswordSite:userName password:userPassword site:@"http://sites/company/IT/iOSTestPicLib"];
    [auth setAuthdelegate:self];
    [auth authenticate];

}
```

And this delegate method gets called no matter what I enter for user name, password, and site (spResponse is an IBOutlet to a UILabel):

``` objective-c
- (void)authentication:(SPClientCallbackDelegate *)didAuthenticate
{
    //NSLog(@"Authenticated successfully");
    [spResponse setText:@"Authenticated Succesfully"];
}
```

Any thoughts?

**Comment by incredibleweirdo** [comment]
Ah, I've found it! I need to implement one of the NSURLConnection delegate methods for authentication challenges, such as connection:didReceiveAuthenticationChallenge, or connection:willSendRequestForAuthenticationChallenge, in FormsAuth.m.

**Comment by jimmywim** [comment]
Hmm that's odd, it shouldn't trigger didAuthenticate if the connection is challenged or otherwise 401'd.

But yeah, there are the other delegates there for NSUrlConnection which you should handle.

The really weird thing though, is that you said you're using domain credentials. Is that Windows Authentication? I've yet to properly implement that, is it working with the FormsAuth class? Didn't think it would - as that uses the Forms authentication web service...

It is seemingly possible to issue NTLM credentials, but like I said I've yet to implement, it's on the backlog.

**Comment by incredibleweirdo** [comment]
It is, oddly, working in the FormsAuth class after I implemented the delegate protocols mentioned above, as well as extending the CookieStore to handle the cookie that Sharepoint sets for domain authentication - WSS_KeepSessionAuthenticated cookie. 

I think the reason (and I'll have to look closely again at this) was because NSURLConnection was calling the delegate protocol connection:didReceiveResponse when it received an authentication challenge, as it wasn't a failure. Simply implementing connection:didReceiveAuthenticationChallenge (and connection:shouldUseCredentialStorage) stopped connection:didReceiveResponse from getting called for the authentication challenge.

**Comment by jonnymunday** [comment]
I too am having the issue that all responses are coming back with a 200 code and hitting didAuthenticate even if the username and password are invalid. I have tried adding the delegate protocols that incredibleweirdo is suggested but they don't get called either. In the response I never get a FedAuth cookie. I'm not sure what I would have to do to implement the Cookie update described so haven't tried that - incredibleweirdo - do you have any source code I could look at? I am trying to connect to SharePoint 2013 that is using Microsoft Forefront UAG to provide Forms Based Authentication. Any help you can provide with this would be much appreciated as I am well and truly stuck!

**Comment by benbruscella** [comment]
I'm seeing a similar but different issue with Forms Auth. Using the @incredibleweirdo fork, when I login successfully, it continues to log that user in regardless of what get's submitted with initWithUsernamePasswordSite.

Any ideas?

**Comment by laurentrivard** [comment]
@benbruscella Have you figured out how to connect successfully yet? I am using @incredibleweirdo 's fork too but I am still having problems.

**Comment by incredibleweirdo** [comment]
Hello,
   I can't say that I can offer much in the way of help. My fork is nothing but a cleanup of two message names to match Objective-C convention. 

  I can say that there were issues with this authentication when we moved from iOS 6 to iOS 7, and what's described above sounds just like it. I ended up implementing alternative delegate protocols to resolve, as seen here: http://stackoverflow.com/questions/18681024/setdefaultcredential-not-working-for-uiwebview-in-ios-7-but-works-fine-in-earlie/19373078#19373078 
  In the project I was working on, I put the mentioned delegate protocol in the SPMobile FormsAuth.m and APIResponseHandler.m implementation files.

**Comment by incredibleweirdo** [comment]
@jonnymunday - here's is the code I edited in CookieStore.m to store the domain authentication cookie:

``` objective-c
+(NSMutableArray *)getSharedAuthCookies:(NSURL *)apiUri
{
    NSDictionary *fedAuthCookie = [NSDictionary dictionaryWithObjectsAndKeys:
                                   apiUri, NSHTTPCookieOriginURL,
                                   @"FedAuth", NSHTTPCookieName,
                                   @"/", NSHTTPCookiePath,
                                   [[CookieStore sharedAuthCookie] fedAuth] , NSHTTPCookieValue,
                                   nil];

    NSDictionary *rtFaCookie = [NSDictionary dictionaryWithObjectsAndKeys:
                                apiUri, NSHTTPCookieOriginURL,
                                @"rtFa", NSHTTPCookieName,
                                @"/", NSHTTPCookiePath,
                                [[CookieStore sharedAuthCookie] rtFa] , NSHTTPCookieValue,
                                nil];

    NSDictionary *wssCookie = [NSDictionary dictionaryWithObjectsAndKeys:
                               apiUri, NSHTTPCookieOriginURL,
                               @"wss", NSHTTPCookieName,
                               @"/", NSHTTPCookiePath,
                               [[CookieStore sharedAuthCookie] wss], NSHTTPCookieValue,
                               nil];


    NSHTTPCookie *fedAuthCookieObj = [NSHTTPCookie cookieWithProperties:fedAuthCookie];
    NSHTTPCookie *rtFaCookieObj = [NSHTTPCookie cookieWithProperties:rtFaCookie];
    NSHTTPCookie *wssCookieObj = [NSHTTPCookie cookieWithProperties:wssCookie];

    NSMutableArray *cookiesArray;
    if ([fedAuthCookie objectForKey:[[CookieStore sharedAuthCookie] fedAuth]] != nil) {
    cookiesArray = [NSMutableArray arrayWithObjects: fedAuthCookieObj, nil];
        if(rtFaCookieObj != nil)
            [cookiesArray addObject:rtFaCookieObj];
    }else{
        cookiesArray = [NSMutableArray arrayWithObjects:wssCookieObj, nil];
    }

    return cookiesArray;
}
```

**Comment by hybridor** [comment]
hello
any update to use with swift?
